In [6]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a = np.array([[22,33,44],[55,66,77],[88,99,11]])

print('初始\n',a)
#与单一数值比较
print(a == 66)

#多数值 and print it!
print (a <= 44)
print (a[a<=44])

#切片
print (a[0:2,1:3])
print (a[...,:2])

#与或
b = (a == 66) | (a == 55)
print('or \n',b)

a[b] = 0
print (a)

初始
 [[22 33 44]
 [55 66 77]
 [88 99 11]]
[[False False False]
 [False  True False]
 [False False False]]
[[ True  True  True]
 [False False False]
 [False False  True]]
[22 33 44 11]
[[33 44]
 [66 77]]
[[22 33]
 [55 66]
 [88 99]]
or 
 [[False False False]
 [ True  True False]
 [False False False]]
[[22 33 44]
 [ 0  0 77]
 [88 99 11]]


In [9]:
s = np.array([['2','3','4'],['5','6','0']])
print(s.dtype)

a = np.array(['1','2','3'])
print (a.dtype)
#print(a.min())

t = s[:,0].astype(float)
print(t)

t = s.astype(int)
print ('type:',t.dtype)
print ('\nvalue:',t)
print (t[:,0].min())

<U1
<U1
[2. 5.]
type: int32

value: [[2 3 4]
 [5 6 0]]
2


In [10]:
#sum!
print (t.sum(axis=1))

print (t.sum(axis=0))

[ 9 11]
[7 9 4]
